### ISSUE TITLE
登录注册逻辑调整

### ISSUE THREAD

**Issue by junyan233** [everforo/everforo-standalone#11]
joining设置
如果是everyone can join，那么放开join入口，新用户通过join或者login正常完成注册后，直接成为会员
如果是need admin approve，同样放开join入口，新用户通过join或者login正常完成注册后，弹出request join弹框，并且弹框不可关闭，刷新页面后，弹框仍然在 
如果是invite only，首先要隐藏join入口，点击右上角的login，输入邮箱后，如果识别出是新用户，建议提示只能通过invite变成member，阻止用户完成后续的注册流程

**Comment by junyan233** [comment]
周一一起讨论


![image](https://user-images.githubusercontent.com/37821776/109252537-c7244500-7828-11eb-89d9-fe10deb081db.png)

**Comment by chenglong1206** [comment]
fix
