### ISSUE TITLE
注册新账号，点击邮箱里面的link，提示"undefined route"

### ISSUE THREAD

**Issue by junyan233** [everforo/everforo-standalone#12]
![image](https://user-images.githubusercontent.com/37821776/109098325-0e90cf80-775c-11eb-9c81-3e2a62d63dc3.png)
![image](https://user-images.githubusercontent.com/37821776/109098336-12245680-775c-11eb-8682-48217c4341a6.png)

**Comment by junyan233** [comment]
点击reset password的link也是一样的报错

**Comment by chenglong1206** [comment]
fix
