### ISSUE TITLE
ban功能失效

### ISSUE THREAD

**Issue by junyan233** [everforo/everforo-standalone#13]
在group home，topic list点击普通用户，用户profile弹框中不显示ban的入口
在members list，点击普通用户，用户profile弹框中不显示ban的入口

在thread页面，点击普通用户，用户profile的弹框中能正常显示ban的入口

![image](https://user-images.githubusercontent.com/37821776/109111893-aef2ee00-7774-11eb-9640-93944cb7b733.png)
![image](https://user-images.githubusercontent.com/37821776/109111902-b4503880-7774-11eb-9930-d34a3eea98b8.png)

**Comment by chenglong1206** [comment]
fix
