### ISSUE TITLE
调整guest点击group home页面左侧Members/Online的效果

### ISSUE THREAD

**Issue by junyan233** [everforo/everforo-standalone#16]
调整guest点击group home页面左侧Members/Online的效果

1.不显示鼠标hover效果

2.或者能点击，点击以后弹出登录注册弹框

![image](https://user-images.githubusercontent.com/37821776/109461867-bb8d8400-7a9d-11eb-9979-1ed2d13f14a7.png)

**Comment by chenglong1206** [comment]
fix
