### ISSUE TITLE
消除everforo的痕迹

### ISSUE THREAD

**Issue by junyan233** [everforo/everforo-standalone#2]
Privacy/Policy@2021 Everforo, Inc./EULA/v1.2要替换成新的，消除everforo的痕迹

后面会做一个新的extension来自定义这些内容

![image](https://user-images.githubusercontent.com/37821776/108810784-dddb5980-75e6-11eb-8c46-d75e01e06e57.png)
![image](https://user-images.githubusercontent.com/37821776/108810804-e92e8500-75e6-11eb-9fcd-2b0934acfa19.png)

**Comment by junyan233** [comment]
invite member中的默认描述

![image](https://user-images.githubusercontent.com/37821776/108815616-b937af80-75ef-11eb-929b-ba30a8f60f71.png)

**Comment by junyan233** [comment]
![image](https://user-images.githubusercontent.com/37821776/108816196-b2f60300-75f0-11eb-8742-a212cf67c680.png)

**Comment by chenglong1206** [comment]
fix

**Comment by junyan233** [comment]
第一个等新的extension做好就能消除
