### ISSUE TITLE
UI优化

### ISSUE THREAD

**Issue by junyan233** [everforo/everforo-standalone#6]
登录注册弹框

![image](https://user-images.githubusercontent.com/37821776/108960676-40992780-76b1-11eb-9776-67e4eaca1312.png)

**Comment by junyan233** [comment]
![image](https://user-images.githubusercontent.com/37821776/108960776-67575e00-76b1-11eb-8325-599d066fa509.png)

**Comment by chenglong1206** [comment]
第二个fix了

**Comment by junyan233** [comment]
![image](https://user-images.githubusercontent.com/37821776/109250677-0486d380-7825-11eb-9102-b0d51e16a0bf.png)

**Comment by junyan233** [comment]
![image](https://user-images.githubusercontent.com/37821776/109250748-25e7bf80-7825-11eb-87b8-cd54dd951616.png)

**Comment by chenglong1206** [comment]
fix
