### ISSUE TITLE
group设置invite only，不应该还显示join入口

### ISSUE THREAD

**Issue by junyan233** [everforo/everforo-standalone#9]
group设置invite only，不应该还显示join入口

![image](https://user-images.githubusercontent.com/37821776/108964734-d4212700-76b6-11eb-9b60-895436d62036.png)

![image](https://user-images.githubusercontent.com/37821776/108964648-b358d180-76b6-11eb-8749-2879e4897156.png)

**Comment by chenglong1206** [comment]
fix
